---
- hosts: all
  become: yes
  tasks:
  - name: update and upgrade
    apt: 
      update_cache: yes
      force_apt_get: yes
      upgrade: dist
      install_recommends: yes
      cache_valid_time: 3600
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  - name: update and upgrade on centos
    yum:
      name: epel-release
      state: latest
      update_cache: yes
      allow_downgrade: yes
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  - name: Create new users
    user:
      name: '{{ item }}'
      shell: /bin/false
      create_home: no
      state: present
    loop:
      - prometheus
      - node_exporter
      - blackbox_exporter
  - name: copy name service
    template: 
      src: '{{ item.src  }}'
      dest: '{{ item.dest }}'
    loop:
      - src: blackbox_exporter.service
        dest: /etc/systemd/system/blackbox_exporter.service
      - src: prometheus.service
        dest: /etc/systemd/system/prometheus.service
      - src: node_exporter.service
        dest: /etc/systemd/system/node_exporter.service
      
  
  - name: Unarchive a file that needs to be downloaded (added in 2.0)
    unarchive:
      src: '{{ item }}'
      dest: /home/
      remote_src: yes
    loop:
      - 'https://github.com/prometheus/prometheus/releases/download/v2.20.1/prometheus-2.20.1.linux-amd64.tar.gz'
      - 'https://github.com/prometheus/blackbox_exporter/releases/download/v0.17.0/blackbox_exporter-0.17.0.linux-amd64.tar.gz'
      - 'https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz'

  - name: Ansible copy files remote to remote
    copy:
      src: '{{ item.src }}'
      dest: '{{ item.dest }}'
      remote_src: yes
      owner: '{{ item.owner }}'
     # mode: '{{ item.mode }}'
      group: '{{ item.group }}'
    loop:
      - src: '/home/prometheus-2.20.1.linux-amd64/prometheus' 
        dest: '/usr/local/bin/prometheus'
        owner: 'prometheus'
      #mode: '744'
        group: 'prometheus'
      - src: '/home/prometheus-2.20.1.linux-amd64/promtool'
        dest: '/usr/local/bin/promtool'
        owner: 'prometheus'
       #mode: '744'
        group: 'prometheus'
      - src: '/home/node_exporter-1.0.1.linux-amd64/node_exporter'
        dest: '/usr/local/bin/node_exporter'
        owner: 'node_exporter'
       #mode: '744'
        group: 'node_exporter'
      - src: '/home/blackbox_exporter-0.17.0.linux-amd64/blackbox_exporter'
        dest: '/usr/local/bin/blackbox_exporter'
        owner: 'blackbox_exporter'
        #mode: ''
        group: 'blackbox_exporter'
  - name: Create a directory if it does not exist
    file:
      path: '{{ item.path }}'
      state: '{{ item.state }}'
      owner: '{{ item.owner }}'
      mode: '0755'
    loop:
      - state: 'directory'
        path: '/var/lib/prometheus'
        owner: 'prometheus'
      - state: 'directory'
        path: '/etc/prometheus'
        owner: 'prometheus'
      - state: 'directory'
        path: '/etc/blackbox_exporter'
        owner: 'blackbox_exporter'
  - name: Ansible copy files remote to remote2
    copy:
      src: '{{ item.src }}'
      dest: '{{ item.dest }}'
      remote_src: '{{ item.remote_src }}'
      owner: '{{ item.owner }}'
    loop:
      - src: 'prometheus.yml'
        dest: '/etc/prometheus/prometheus.yml'
        remote_src: 'no'
        owner: 'prometheus'
      - src: '/home/blackbox_exporter-0.17.0.linux-amd64/blackbox.yml'
        dest: '/etc/blackbox_exporter/blackbox.yml'
        remote_src: 'yes'
        owner: 'blackbox_exporter'
        
  - name: just force systemd to reread configs (2.4 and above)
    systemd:
      daemon_reload: yes

  - name: restart service s, in all cases, also issue daemon-reload to pick up config changes
    systemd:
      state: restarted
      daemon_reload: yes
      name: '{{ item.name }}'
    loop:
      - name: 'prometheus.service'
      - name: 'blackbox_exporter.service'
      - name: 'node_exporter.service'




