# Rules and alerts are read from the specified file(s)
#rule_files:
# - rules.yml
#alerting:
#  alertmanagers:
#  - static_configs:
#    - targets:
#      - localhost:9093
#
scrape_configs:
  - job_name: 'federate'
    scrape_interval: 15s

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{job="prometheus"}'
        - '{__name__=~"job:.*"}'

    static_configs:
      - targets:
        - '185.212.129.132:9090'
        - '185.14.30.169:9090'
        #- 'source-prometheus-3:9090'

          ##scrape_configs:
          #  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
          #  - job_name: 'prometheus'
          #
          #    # Override the global default and scrape targets from this job every 5 seconds.
          #    scrape_interval: 5s
          #    scrape_timeout: 5s
          #
          #    # metrics_path defaults to '/metrics'
          #    # scheme defaults to 'http'.
          #    honor_labels: true
          #    metrics_path: '/federate'
          #
          #    params:
          #      'match[]':
          #        - '{job="prometheus"}'
          #        - '{__name__=~"job:.*"}'
          #    #static_configs:
          #    #  - targets: ['localhost:9090']
          #    static_configs:
          #      - targets:
          #        - 64.188.20.539090
          #        - 45.128.132.27:9090
          #          #- 45.188.20.53:9090

                                               
          #  - job_name: 'node_exporter'
          #    scrape_interval: 5s
          #    static_configs:
          #      - targets: ['localhost:9100']
          #
          #
          #
          #  - job_name: 'blackbox'
          #    metrics_path: /probe
          #    params:
          #      module: [http_2xx]
          #
          #
          #    static_configs:
          #      - targets:
          #         - https://www.telegraph.co.uk
          #         - https://i.ua
          #         - https://ya.ru
          #         - https://pornhub.com
          #         - https://roulette77.us
          #         - http://azino-777x.ru
          #    relabel_configs:
          #      - source_labels: [__address__]
          #        target_label: __param_target
          #      - source_labels: [__param_target]
          #        target_label: instance
          #      - target_label: __address__
          #        replacement: 127.0.0.1:9115
          #
          #
          #





 
