version: '3'

services:

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Qa37847854854895894
      - POSTGRES_DB=db1
    volumes:
      - pgdata1:/var/lib/postgresql/data/
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
volumes:
  pgdata1:
